#!/bin/bash

echo "🔍 Prüfe, ob Docker installiert ist..."
if command -v docker &> /dev/null; then
    echo "✅ Docker ist bereits installiert."
    docker --version
else

    # System vorbereiten
    sudo apt-get update
    sudo apt-get install -y ca-certificates curl gnupg lsb-release

    # Docker GPG-Key hinzufügen
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
    sudo chmod a+r /etc/apt/keyrings/docker.asc

    # Docker-Repository hinzufügen
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    # Docker installieren
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

fi

sudo usermod -aG docker "${USER}"

