- name: Warten, bis NPM erreichbar ist und Login erfolgreich
  ansible.builtin.uri:
    url: http://localhost:81/api/tokens
    method: POST
    body_format: json
    headers:
      Content-Type: application/json
    body:
      identity: "admin@example.com"
      secret: "changeme"
    return_content: yes
  register: npm_auth
  retries: 3
  delay: 10
  until: npm_auth.status == 200
  ignore_errors: false


- name: Login to NPM
  ansible.builtin.uri:
    url: http://localhost:81/api/tokens
    method: POST
    body_format: json
    headers:
      Content-Type: application/json
    body:
      identity: "admin@example.com"
      secret: "changeme"
    return_content: yes
  register: npm_auth

- name: Create proxy host
  ansible.builtin.uri:
    url: http://localhost:81/api/nginx/proxy-hosts
    method: POST
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ npm_auth.json.token }}"
    body:
      domain_names: ["dummy.local"]
      forward_scheme: "http"
      forward_host: "apache"
      forward_port: 80
      access_list_id: null
      certificate_id: null
      ssl_forced: false
      caching_enabled: false
      block_exploits: true
      advanced_config: ""
      locations: []
      allow_websocket_upgrade: false
      http2_support: false
      hsts_enabled: false
      hsts_subdomains: false
      locations: []
    status_code: 200,201

