- name: Ensure UFW is installed
  ansible.builtin.package:
    name: ufw
    state: present

- name: Allow SSH (Port 22)
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow HTTP (Port 80)
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS (Port 443)
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Allow Nginx port (Port 81)
  community.general.ufw:
    rule: allow
    port: 81
    proto: tcp

- name: Enable UFW (only if not already enabled)
  community.general.ufw:
    state: enabled

- name: Install SSH key for remote user
  ansible.posix.authorized_key:
    user: leon
    state: present
    key: "{{ lookup('file', 'id_ansible.pub') }}"
