---
- name: Copy docker-compose.yaml file
  ansible.builtin.copy:
    src: docker-compose.yaml
    dest: /root/docker-compose.yaml
    mode: '0755'

- name: start docker compose with config
  ansible.builtin.command:
    cmd: docker compose -f /root/docker-compose.yaml up -d
